### PR TITLE
D5: Addition of document and bug fix 

### LINKED ISSUE #22: D5: End-to-end testing
This issue is to track unit testing for the D5 assignment. 
Bugs/Issues found through end to end testing: 
#31 (fixed) 
#30 (fixed) 
#29 (not enough time to fix 
#24 (in progress) 
#34 (not enough time to fix)

### LINKED ISSUE #23: D5: Cognitive walkthrough
This is a tracker for the other part of my D5, cognitive walkthrough. 
Bugs/issues found through cognitive walkthrough: 
#32 (fixed) 
#28 (fixed) 
#25 (fixed)

### LINKED ISSUE #24: D5: End to End:  >100% Matches
The dataframe ingredients strings can be searched more than once per to create nonsensical percentage matches. 

For example: 

User input = ['1', 'cup', 'grain'] 
Dataframe = ['1 cup starch', 'grain'] 

The match list would produce: ['1', 'cup', 'grain'], which generates a 3/2 match.

### LINKED ISSUE #32: D5: Cognitive Walkthrough: Addition of Matches to dataframe
Split from the addition of url and matches.

### PR DESCRIPTION
**Pull request by schweinsbergs**
Added part of the documentation for D5-- Up to the cognitive walkthrough reflection. 

Adds the enhancement for #32

### CODE REVIEW

**Comment by schweinsbergs** [comment]
Latest push fixes #24 , but has created #34.

**Comment by schweinsbergs** [comment]
D5 document is done, this is the submission. Linking #23 and #22 because they're my trackers for D5 progress.

**Comment by schweinsbergs** [comment]
Final markdown file added with the links for my video and presentation.

**Review by alfarozavalae — APPROVED** [review]
I agree that the cognitive walk through was needed specially because you had already been doing unit testing. End to end is a second good choice and I like the reasoning you provided for it too. 
For the cognitive walk through, I liked your documentation in the worksheets and I appreciate how you selected people of different backgrounds such as someone with great computer literacy and someone with little. 
Good work documenting the bugs as you found them and working on fixing them too. I understand that some bugs are harder to fix but if you would have started testing a tiny bit earlier, I believe you could have gotten some more bugs resolved because you would have had more time to debug. 
In general, for the E2E and cognitive walk through , it would have been helpful to see visuals of how each testing was performed. 
Overall, really good job adding all the parts in this deliverable. You put a lot of work into this and it shows!

PR is approved so you can merge it.

**Pull request merged**
